/**
 * ETAGIA LMS — Catalogue Khan Academy Français
 * Modules de formation en ligne, 100% en français
 * Source : fr.khanacademy.org + YouTube KA Francophone
 */

export type KAKind = 'video' | 'exercise' | 'article' | 'course'
export type KALevel = 'débutant' | 'intermédiaire' | 'avancé'

export interface KAModule {
  id: string
  title: string
  description: string
  kind: KAKind
  level: KALevel
  duration?: string          // ex: "12 min"
  domain: string             // slug de la catégorie
  tags: string[]
  /** ID YouTube si c'est une vidéo embedable */
  youtubeId?: string
  /** URL de la playlist YouTube (pour les cours) */
  playlistId?: string
  /** Lien direct fr.khanacademy.org */
  kaUrl: string
  thumbnail?: string
}

export interface KADomain {
  id: string
  label: string
  icon: string
  color: string             // tailwind gradient from
  colorTo: string           // tailwind gradient to
  description: string
  moduleCount?: number
}

/* ── Domaines de formation ─────────────────────────────────────────────────── */
export const KA_DOMAINS: KADomain[] = [
  {
    id: 'informatique',
    label: 'Informatique & Programmation',
    icon: '💻',
    color: 'from-blue-600',
    colorTo: 'to-cyan-500',
    description: 'Programmation, algorithmes, web, intelligence artificielle',
  },
  {
    id: 'finance',
    label: 'Finance & Économie',
    icon: '📈',
    color: 'from-emerald-600',
    colorTo: 'to-teal-500',
    description: 'Comptabilité, marchés financiers, microéconomie, macroéconomie',
  },
  {
    id: 'entrepreneuriat',
    label: 'Entrepreneuriat & Gestion',
    icon: '🚀',
    color: 'from-orange-600',
    colorTo: 'to-amber-500',
    description: 'Création d\'entreprise, marketing, stratégie, leadership',
  },
  {
    id: 'maths',
    label: 'Mathématiques Appliquées',
    icon: '📐',
    color: 'from-violet-600',
    colorTo: 'to-purple-500',
    description: 'Statistiques, probabilités, algèbre linéaire, analyse',
  },
  {
    id: 'sciences',
    label: 'Sciences Appliquées',
    icon: '🔬',
    color: 'from-rose-600',
    colorTo: 'to-pink-500',
    description: 'Physique, chimie, biologie, santé — niveau professionnel',
  },
  {
    id: 'numerique',
    label: 'Culture Numérique',
    icon: '🌐',
    color: 'from-sky-600',
    colorTo: 'to-indigo-500',
    description: 'Internet, cybersécurité, données, intelligence artificielle',
  },
]

/* ── Catalogue des modules ─────────────────────────────────────────────────── */
export const KA_MODULES: KAModule[] = [

  /* ════════════════ INFORMATIQUE & PROGRAMMATION ════════════════ */
  {
    id: 'info-01',
    title: 'Introduction à la programmation',
    description: 'Découvrez les bases de la programmation : variables, boucles, fonctions. Parfait pour démarrer sans aucune expérience préalable.',
    kind: 'course',
    level: 'débutant',
    duration: '2h30',
    domain: 'informatique',
    tags: ['programmation', 'bases', 'algorithmique'],
    playlistId: 'PLbnELaJPJVmAD08TkxSg6k4S8HDAF5rYi',
    kaUrl: 'https://fr.khanacademy.org/computing/computer-programming/programming',
  },
  {
    id: 'info-02',
    title: 'Algorithmique et pensée computationnelle',
    description: 'Apprenez à résoudre des problèmes complexes avec des algorithmes. Recherche, tri, récursivité expliqués simplement.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h',
    domain: 'informatique',
    tags: ['algorithmes', 'logique', 'résolution de problèmes'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-science/algorithms',
  },
  {
    id: 'info-03',
    title: 'HTML & CSS — Créer des pages web',
    description: 'Construisez vos premières pages web en HTML et stylisez-les avec CSS. De la structure à la mise en forme.',
    kind: 'course',
    level: 'débutant',
    duration: '4h',
    domain: 'informatique',
    tags: ['web', 'HTML', 'CSS', 'développement'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-programming/html-css',
  },
  {
    id: 'info-04',
    title: 'JavaScript — Programmation Web Interactive',
    description: 'Rendez vos pages web dynamiques avec JavaScript. Événements, DOM, fonctions, objets.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '5h',
    domain: 'informatique',
    tags: ['JavaScript', 'web', 'interactivité'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-programming/html-css-js',
  },
  {
    id: 'info-05',
    title: 'SQL — Bases de données relationnelles',
    description: 'Maîtrisez le langage SQL pour interroger, manipuler et gérer des bases de données.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h30',
    domain: 'informatique',
    tags: ['SQL', 'bases de données', 'données'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-programming/sql',
  },
  {
    id: 'info-06',
    title: 'Cryptographie et Cybersécurité',
    description: 'Comprendre le chiffrement, les protocoles de sécurité et comment protéger les données numériques.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '2h',
    domain: 'informatique',
    tags: ['sécurité', 'cryptographie', 'données'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-science/cryptography',
  },
  {
    id: 'info-07',
    title: 'Intelligence Artificielle — Les fondamentaux',
    description: 'Introduction à l\'IA : machine learning, réseaux de neurones, applications pratiques.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '2h30',
    domain: 'informatique',
    tags: ['IA', 'machine learning', 'données'],
    kaUrl: 'https://fr.khanacademy.org/computing/ap-computer-science-principles/data-analysis-101',
  },
  {
    id: 'info-08',
    title: 'Réseaux informatiques — Fonctionnement d\'Internet',
    description: 'Comment fonctionne Internet ? DNS, HTTP, protocoles TCP/IP expliqués clairement.',
    kind: 'video',
    level: 'débutant',
    duration: '45 min',
    domain: 'informatique',
    tags: ['réseaux', 'internet', 'protocoles'],
    youtubeId: 'AEaKrq3SpW8',
    kaUrl: 'https://fr.khanacademy.org/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet',
  },
  {
    id: 'info-09',
    title: 'Programmation Orientée Objet',
    description: 'Maîtrisez les concepts POO : classes, héritage, encapsulation, polymorphisme.',
    kind: 'course',
    level: 'avancé',
    duration: '3h',
    domain: 'informatique',
    tags: ['POO', 'programmation', 'architecture'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-programming/programming-natural-simulations',
  },
  {
    id: 'info-10',
    title: 'Structures de données essentielles',
    description: 'Tableaux, listes chaînées, piles, files, arbres et graphes : tout ce qu\'un développeur doit savoir.',
    kind: 'course',
    level: 'avancé',
    duration: '4h',
    domain: 'informatique',
    tags: ['structures de données', 'algorithmique', 'programmation'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-science/algorithms/binary-search/a/binary-search',
  },
  {
    id: 'info-11',
    title: 'Créer une application web — Projet complet',
    description: 'Construisez une application web de A à Z en combinant HTML, CSS et JavaScript.',
    kind: 'course',
    level: 'avancé',
    duration: '6h',
    domain: 'informatique',
    tags: ['projet', 'web', 'développement complet'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-programming/html-js-jquery',
  },
  {
    id: 'info-12',
    title: 'Représentation de l\'information numérique',
    description: 'Binaire, hexadécimal, encodages : comment l\'ordinateur stocke et traite l\'information.',
    kind: 'video',
    level: 'débutant',
    duration: '30 min',
    domain: 'informatique',
    tags: ['binaire', 'numérique', 'fondamentaux'],
    youtubeId: 'Xpk67YzOn5w',
    kaUrl: 'https://fr.khanacademy.org/computing/ap-computer-science-principles/computers-101',
  },

  /* ════════════════ FINANCE & ÉCONOMIE ════════════════ */
  {
    id: 'fin-01',
    title: 'Introduction à la comptabilité',
    description: 'Bilan, compte de résultat, flux de trésorerie. Comprendre les états financiers d\'une entreprise.',
    kind: 'course',
    level: 'débutant',
    duration: '3h',
    domain: 'finance',
    tags: ['comptabilité', 'bilan', 'entreprise'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/core-finance/accounting-and-financial-statements',
  },
  {
    id: 'fin-02',
    title: 'Marchés financiers et investissement',
    description: 'Actions, obligations, fonds, marchés boursiers. Comment fonctionnent les marchés de capitaux.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '4h',
    domain: 'finance',
    tags: ['investissement', 'bourse', 'marchés'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/core-finance/stock-and-bonds',
  },
  {
    id: 'fin-03',
    title: 'Microéconomie — Offre, demande et marchés',
    description: 'Analyse des comportements économiques individuels : consommateurs, entreprises, prix d\'équilibre.',
    kind: 'course',
    level: 'débutant',
    duration: '5h',
    domain: 'finance',
    tags: ['microéconomie', 'offre', 'demande', 'marchés'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/microeconomics',
  },
  {
    id: 'fin-04',
    title: 'Macroéconomie — PIB, chômage, inflation',
    description: 'Comprendre l\'économie nationale : indicateurs macroéconomiques, politiques monétaires et budgétaires.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '5h',
    domain: 'finance',
    tags: ['macroéconomie', 'PIB', 'politique économique'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/macroeconomics',
  },
  {
    id: 'fin-05',
    title: 'Finance d\'entreprise',
    description: 'Valorisation d\'entreprise, coût du capital, analyse de projets, décisions de financement.',
    kind: 'course',
    level: 'avancé',
    duration: '6h',
    domain: 'finance',
    tags: ['finance', 'valorisation', 'investissement'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/core-finance/corporate-finance',
  },
  {
    id: 'fin-06',
    title: 'Systèmes bancaires et monnaie',
    description: 'Comment les banques créent la monnaie, rôle des banques centrales, systèmes de paiement.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h',
    domain: 'finance',
    tags: ['banque', 'monnaie', 'crédit'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/core-finance/money-and-banking',
  },
  {
    id: 'fin-07',
    title: 'Gestion du budget personnel',
    description: 'Planifier ses finances, épargner, investir, éviter les pièges de l\'endettement.',
    kind: 'course',
    level: 'débutant',
    duration: '2h',
    domain: 'finance',
    tags: ['budget', 'épargne', 'finance personnelle'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/personal-finance',
  },
  {
    id: 'fin-08',
    title: 'Commerce international et mondialisation',
    description: 'Échanges commerciaux, avantages comparatifs, balance des paiements, impact de la mondialisation.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h',
    domain: 'finance',
    tags: ['commerce', 'international', 'mondialisation'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/macroeconomics/international-trade-topic',
  },
  {
    id: 'fin-09',
    title: 'Analyse financière — Lire les états financiers',
    description: 'Ratios financiers, analyse de liquidité, rentabilité, solvabilité d\'une entreprise.',
    kind: 'course',
    level: 'avancé',
    duration: '4h',
    domain: 'finance',
    tags: ['analyse', 'ratios', 'états financiers'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/core-finance/accounting-and-financial-statements/financial-ratios-tutorial',
  },
  {
    id: 'fin-10',
    title: 'Économie du développement — Afrique et pays émergents',
    description: 'Croissance économique, pauvreté, inégalités, politiques de développement dans les pays émergents.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h30',
    domain: 'finance',
    tags: ['développement', 'Afrique', 'émergents', 'croissance'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/macroeconomics/economic-indicators-and-the-business-cycle',
  },

  /* ════════════════ ENTREPRENEURIAT & GESTION ════════════════ */
  {
    id: 'ent-01',
    title: 'Créer son entreprise — De l\'idée au lancement',
    description: 'Étapes clés pour créer une entreprise : idée, étude de marché, business plan, statut juridique, financement.',
    kind: 'course',
    level: 'débutant',
    duration: '3h',
    domain: 'entrepreneuriat',
    tags: ['création', 'startup', 'business plan'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers',
  },
  {
    id: 'ent-02',
    title: 'Marketing digital — Stratégies et outils',
    description: 'SEO, réseaux sociaux, email marketing, publicité en ligne. Acquérir et fidéliser des clients.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '4h',
    domain: 'entrepreneuriat',
    tags: ['marketing', 'digital', 'clients', 'SEO'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/growing-a-business',
  },
  {
    id: 'ent-03',
    title: 'Gestion de projet — Méthodes agiles',
    description: 'Scrum, Kanban, gestion des parties prenantes, planification, suivi et livraison de projets.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h30',
    domain: 'entrepreneuriat',
    tags: ['projet', 'agile', 'scrum', 'management'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/project-management',
  },
  {
    id: 'ent-04',
    title: 'Leadership et management d\'équipe',
    description: 'Développer son leadership, motiver une équipe, gérer les conflits, communication managériale.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '2h30',
    domain: 'entrepreneuriat',
    tags: ['leadership', 'management', 'équipe'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/soft-skills',
  },
  {
    id: 'ent-05',
    title: 'Business Model Canvas — Concevoir son modèle',
    description: 'Utiliser le Business Model Canvas pour concevoir, tester et faire évoluer votre modèle d\'affaires.',
    kind: 'video',
    level: 'débutant',
    duration: '45 min',
    domain: 'entrepreneuriat',
    tags: ['business model', 'canvas', 'stratégie'],
    youtubeId: 'IP0cUBWTgpY',
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/growing-a-business',
  },
  {
    id: 'ent-06',
    title: 'Négociation et vente',
    description: 'Techniques de vente, cycles de négociation, closing, gestion des objections client.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '2h',
    domain: 'entrepreneuriat',
    tags: ['vente', 'négociation', 'clients'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/soft-skills',
  },
  {
    id: 'ent-07',
    title: 'Stratégie d\'entreprise',
    description: 'Analyse SWOT, 5 forces de Porter, avantage concurrentiel, positionnement stratégique.',
    kind: 'course',
    level: 'avancé',
    duration: '3h',
    domain: 'entrepreneuriat',
    tags: ['stratégie', 'compétitivité', 'analyse'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/growing-a-business',
  },
  {
    id: 'ent-08',
    title: 'Communication professionnelle efficace',
    description: 'Prise de parole en public, rédaction professionnelle, présentation, communication interpersonnelle.',
    kind: 'course',
    level: 'débutant',
    duration: '2h',
    domain: 'entrepreneuriat',
    tags: ['communication', 'présentation', 'rédaction'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/soft-skills',
  },
  {
    id: 'ent-09',
    title: 'E-commerce — Vendre en ligne',
    description: 'Créer une boutique en ligne, gestion des stocks, logistique, paiements, fidélisation.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h',
    domain: 'entrepreneuriat',
    tags: ['e-commerce', 'vente en ligne', 'digital'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/growing-a-business',
  },
  {
    id: 'ent-10',
    title: 'Financer son projet — Levée de fonds',
    description: 'Bootstrapping, love money, business angels, VC, crowdfunding. Préparer sa levée de fonds.',
    kind: 'course',
    level: 'avancé',
    duration: '2h30',
    domain: 'entrepreneuriat',
    tags: ['financement', 'levée de fonds', 'investisseurs'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/core-finance/corporate-finance',
  },

  /* ════════════════ MATHÉMATIQUES APPLIQUÉES ════════════════ */
  {
    id: 'math-01',
    title: 'Statistiques descriptives',
    description: 'Moyenne, médiane, écart-type, distribution, représentations graphiques. Analyser et décrire des données.',
    kind: 'course',
    level: 'débutant',
    duration: '3h',
    domain: 'maths',
    tags: ['statistiques', 'données', 'analyse'],
    kaUrl: 'https://fr.khanacademy.org/math/statistics-probability/summarizing-quantitative-data',
  },
  {
    id: 'math-02',
    title: 'Probabilités appliquées',
    description: 'Calcul des probabilités, lois de probabilité, espérance, variance. Applications pratiques.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '4h',
    domain: 'maths',
    tags: ['probabilités', 'risque', 'statistiques'],
    kaUrl: 'https://fr.khanacademy.org/math/statistics-probability/probability-library',
  },
  {
    id: 'math-03',
    title: 'Algèbre linéaire — Matrices et vecteurs',
    description: 'Matrices, systèmes d\'équations, transformations linéaires, espace vectoriel. Fondement pour l\'IA.',
    kind: 'course',
    level: 'avancé',
    duration: '6h',
    domain: 'maths',
    tags: ['algèbre', 'matrices', 'IA', 'data science'],
    kaUrl: 'https://fr.khanacademy.org/math/linear-algebra',
  },
  {
    id: 'math-04',
    title: 'Inférence statistique',
    description: 'Tests d\'hypothèses, intervalles de confiance, régression linéaire, corrélation.',
    kind: 'course',
    level: 'avancé',
    duration: '5h',
    domain: 'maths',
    tags: ['inférence', 'tests', 'régression'],
    kaUrl: 'https://fr.khanacademy.org/math/statistics-probability/significance-tests-one-sample',
  },
  {
    id: 'math-05',
    title: 'Mathématiques financières',
    description: 'Intérêts composés, annuités, actualisation, valeur temps de l\'argent.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h',
    domain: 'maths',
    tags: ['finance', 'intérêts', 'calcul financier'],
    kaUrl: 'https://fr.khanacademy.org/economics-finance-domain/core-finance/interest-tutorial',
  },
  {
    id: 'math-06',
    title: 'Logique et raisonnement mathématique',
    description: 'Démonstration, induction, raisonnement par l\'absurde. Développer la pensée logique.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '2h30',
    domain: 'maths',
    tags: ['logique', 'raisonnement', 'démonstration'],
    kaUrl: 'https://fr.khanacademy.org/math/cc-sixth-grade-math/cc-6th-factors-and-multiples',
  },
  {
    id: 'math-07',
    title: 'Calcul différentiel et intégral',
    description: 'Dérivées, intégrales, optimisation. Applications en économie, physique et ingénierie.',
    kind: 'course',
    level: 'avancé',
    duration: '8h',
    domain: 'maths',
    tags: ['calcul', 'dérivées', 'optimisation'],
    kaUrl: 'https://fr.khanacademy.org/math/calculus-1',
  },
  {
    id: 'math-08',
    title: 'Mathématiques discrètes pour l\'informatique',
    description: 'Combinatoire, théorie des graphes, logique booléenne — fondements théoriques de l\'informatique.',
    kind: 'course',
    level: 'avancé',
    duration: '5h',
    domain: 'maths',
    tags: ['maths discrètes', 'graphes', 'informatique'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/what-is-modular-arithmetic',
  },

  /* ════════════════ SCIENCES APPLIQUÉES ════════════════ */
  {
    id: 'sci-01',
    title: 'Physique — Mécanique et énergie',
    description: 'Cinématique, dynamique, travail et énergie, conservation de l\'énergie. Niveau BTS/Licence.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '5h',
    domain: 'sciences',
    tags: ['physique', 'mécanique', 'énergie'],
    kaUrl: 'https://fr.khanacademy.org/science/physics/work-energy-power',
  },
  {
    id: 'sci-02',
    title: 'Chimie — Réactions et transformations',
    description: 'Réactions chimiques, stœchiométrie, équilibre, cinétique. Applications industrielles.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '4h',
    domain: 'sciences',
    tags: ['chimie', 'réactions', 'industrie'],
    kaUrl: 'https://fr.khanacademy.org/science/chemistry/chemical-reactions-stoichiome',
  },
  {
    id: 'sci-03',
    title: 'Biologie cellulaire et moléculaire',
    description: 'ADN, ARN, protéines, mitose, méiose. Fondements pour les formations en santé et biotechnologies.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '5h',
    domain: 'sciences',
    tags: ['biologie', 'ADN', 'cellules', 'santé'],
    kaUrl: 'https://fr.khanacademy.org/science/ap-biology/gene-expression-and-regulation',
  },
  {
    id: 'sci-04',
    title: 'Électricité et électronique',
    description: 'Circuits électriques, loi d\'Ohm, composants électroniques. Base pour l\'ingénierie et la domotique.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '4h',
    domain: 'sciences',
    tags: ['électricité', 'circuits', 'ingénierie'],
    kaUrl: 'https://fr.khanacademy.org/science/physics/circuits-topic',
  },
  {
    id: 'sci-05',
    title: 'Énergie solaire et énergies renouvelables',
    description: 'Fonctionnement des panneaux solaires, éoliennes, stockage. Opportunités en Afrique.',
    kind: 'course',
    level: 'débutant',
    duration: '2h30',
    domain: 'sciences',
    tags: ['énergie', 'solaire', 'renouvelable', 'Afrique'],
    kaUrl: 'https://fr.khanacademy.org/science/physics/thermodynamics',
  },
  {
    id: 'sci-06',
    title: 'Santé publique et épidémiologie',
    description: 'Indicateurs de santé, prévention, épidémies, système de santé. Essentiel pour les professionnels de santé.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '3h',
    domain: 'sciences',
    tags: ['santé', 'épidémiologie', 'prévention'],
    kaUrl: 'https://fr.khanacademy.org/science/health-and-medicine',
  },
  {
    id: 'sci-07',
    title: 'Environnement et développement durable',
    description: 'Changement climatique, biodiversité, éco-systèmes, politiques environnementales.',
    kind: 'course',
    level: 'débutant',
    duration: '2h',
    domain: 'sciences',
    tags: ['environnement', 'climat', 'développement durable'],
    kaUrl: 'https://fr.khanacademy.org/science/biology/ecology/intro-to-ecosystems/a/what-is-an-ecosystem',
  },
  {
    id: 'sci-08',
    title: 'Nutrition et physiologie humaine',
    description: 'Métabolisme, nutrition, systèmes physiologiques. Base pour les formations en santé et sport.',
    kind: 'course',
    level: 'débutant',
    duration: '3h',
    domain: 'sciences',
    tags: ['nutrition', 'santé', 'physiologie'],
    kaUrl: 'https://fr.khanacademy.org/science/health-and-medicine/human-anatomy-and-physiology',
  },

  /* ════════════════ CULTURE NUMÉRIQUE ════════════════ */
  {
    id: 'num-01',
    title: 'Comment fonctionne Internet',
    description: 'DNS, HTTP/HTTPS, navigateurs, serveurs, cloud. Comprendre l\'infrastructure numérique moderne.',
    kind: 'course',
    level: 'débutant',
    duration: '1h30',
    domain: 'numerique',
    tags: ['internet', 'web', 'infrastructure'],
    youtubeId: 'AEaKrq3SpW8',
    kaUrl: 'https://fr.khanacademy.org/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet',
  },
  {
    id: 'num-02',
    title: 'Protection des données et vie privée',
    description: 'RGPD, données personnelles, cookies, droits numériques. Indispensable pour tout professionnel.',
    kind: 'course',
    level: 'débutant',
    duration: '1h30',
    domain: 'numerique',
    tags: ['RGPD', 'données', 'vie privée', 'droits'],
    kaUrl: 'https://fr.khanacademy.org/computing/computers-and-internet/xcae6f4a7ff015e7d:online-data-security',
  },
  {
    id: 'num-03',
    title: 'Intelligence Artificielle — Enjeux et applications',
    description: 'IA générative, ChatGPT, automatisation, impacts sur les métiers. Comprendre la révolution IA.',
    kind: 'course',
    level: 'débutant',
    duration: '2h',
    domain: 'numerique',
    tags: ['IA', 'ChatGPT', 'automatisation', 'futur du travail'],
    kaUrl: 'https://fr.khanacademy.org/computing/ap-computer-science-principles',
  },
  {
    id: 'num-04',
    title: 'Cybersécurité — Protéger son entreprise',
    description: 'Phishing, ransomware, mots de passe, VPN, bonnes pratiques de sécurité informatique.',
    kind: 'course',
    level: 'débutant',
    duration: '2h',
    domain: 'numerique',
    tags: ['cybersécurité', 'phishing', 'protection'],
    kaUrl: 'https://fr.khanacademy.org/computing/computers-and-internet/xcae6f4a7ff015e7d:cybersecurity',
  },
  {
    id: 'num-05',
    title: 'Data Science — Introduction à l\'analyse de données',
    description: 'Collecter, nettoyer, analyser et visualiser des données. Outils : tableurs, Python de base.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '4h',
    domain: 'numerique',
    tags: ['data science', 'données', 'analyse', 'Python'],
    kaUrl: 'https://fr.khanacademy.org/computing/ap-computer-science-principles/data-analysis-101',
  },
  {
    id: 'num-06',
    title: 'Accessibilité numérique',
    description: 'Concevoir des produits numériques accessibles à tous : standards WCAG, design inclusif.',
    kind: 'course',
    level: 'intermédiaire',
    duration: '1h30',
    domain: 'numerique',
    tags: ['accessibilité', 'design', 'inclusion'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-programming/html-css/web-development-tools/a/using-the-browser-developer-tools',
  },
  {
    id: 'num-07',
    title: 'Outils de productivité numérique',
    description: 'Google Workspace, Notion, Trello, Slack — maîtriser les outils du travail collaboratif moderne.',
    kind: 'course',
    level: 'débutant',
    duration: '1h30',
    domain: 'numerique',
    tags: ['productivité', 'outils', 'collaboration'],
    kaUrl: 'https://fr.khanacademy.org/college-careers-more/careers/tech-careers',
  },
  {
    id: 'num-08',
    title: 'Blockchain et technologies décentralisées',
    description: 'Fonctionnement de la blockchain, smart contracts, applications décentralisées, opportunités business.',
    kind: 'course',
    level: 'avancé',
    duration: '2h30',
    domain: 'numerique',
    tags: ['blockchain', 'web3', 'décentralisation'],
    kaUrl: 'https://fr.khanacademy.org/computing/computer-science/cryptography',
  },
]

/* ── Helpers ───────────────────────────────────────────────────────────────── */

export function getModulesByDomain(domainId: string): KAModule[] {
  return KA_MODULES.filter(m => m.domain === domainId)
}

export function searchModules(query: string): KAModule[] {
  const q = query.toLowerCase().trim()
  if (!q) return KA_MODULES
  return KA_MODULES.filter(m =>
    m.title.toLowerCase().includes(q) ||
    m.description.toLowerCase().includes(q) ||
    m.tags.some(t => t.toLowerCase().includes(q))
  )
}

export function getDomainWithCount(): (KADomain & { count: number })[] {
  return KA_DOMAINS.map(d => ({
    ...d,
    count: KA_MODULES.filter(m => m.domain === d.id).length,
  }))
}

export const LEVEL_COLORS: Record<KALevel, string> = {
  débutant:      'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  intermédiaire: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
  avancé:        'bg-rose-500/20 text-rose-400 border-rose-500/30',
}

export const KIND_ICONS: Record<KAKind, string> = {
  video:    '▶',
  exercise: '✏️',
  article:  '📄',
  course:   '📚',
}
